# Generated by Django 4.2.7 on 2023-11-24 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followee",
            field=models.ManyToManyField(blank=True, related_name="follower", to=settings.AUTH_USER_MODEL),
        ),
    ]
